language: java
jdk:
  - oraclejdk8
  - oraclejdk7
env:
  - SAMPLE=cxf
  - SAMPLE=mockserver
script: "cd $SAMPLE && mvn --errors --batch-mode clean verify"
notifications:
    email:
        - martin.hofmannsobik@1und1.de
